import { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeAsiaAustralia,
  HiOutlineRocketLaunch,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
} from "react-icons/pi";

import {
  SiJavascript,
  SiNextdotjs,
  SiFigma,
  SiSupabase,
  SiTypescript,
  SiNodedotjs,
  SiExpress,
  SiNestjs,
  SiReact,
  SiPython,
  SiPostgresql,
  SiMysql,
  SiRedis,
  SiDocker,
  SiJest,
  SiPostman,
  SiOpenai,
  SiSwagger,
  SiCypress,
  SiSequelize,
  SiGithubactions,
  SiVercel,
  SiFastapi,
  SiFlask,
  SiMongodb,
  SiFirebase,
  SiKubernetes,
  SiAmazonwebservices,
  SiNginx,
  SiRabbitmq,
  SiApachekafka,
} from "react-icons/si";

import { FaDiscord, FaGithub, FaLinkedin, FaX, FaThreads, FaInstagram, FaXTwitter, FaFacebook, FaPinterest, FaWhatsapp, FaReddit, FaTelegram, } from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeAsiaAustralia,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  typescript: SiTypescript,
  nodejs: SiNodedotjs,
  express: SiExpress,
  nestjs: SiNestjs,
  react: SiReact,
  python: SiPython,
  postgresql: SiPostgresql,
  mysql: SiMysql,
  redis: SiRedis,
  docker: SiDocker,
  jest: SiJest,
  postman: SiPostman,
  openai: SiOpenai,
  swagger: SiSwagger,
  cypress: SiCypress,
  sequelize: SiSequelize,
  githubactions: SiGithubactions,
  vercel: SiVercel,
  fastapi: SiFastapi,
  flask: SiFlask,
  mongodb: SiMongodb,
  firebase: SiFirebase,
  kubernetes: SiKubernetes,
  aws: SiAmazonwebservices,
  nginx: SiNginx,
  rabbitmq: SiRabbitmq,
  kafka: SiApachekafka,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  instagram: FaInstagram,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
